In [1]:
import numpy as np


In [2]:
a = np.array([1, 2, 3]);

In [3]:
type(a)

numpy.ndarray

In [4]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
a

array([1, 2, 3])

In [12]:
a.T

array([1, 2, 3])

In [13]:
# メモリ上の位置
a.data

In [14]:
a.dtype

dtype('int64')

In [17]:
# b を 1 次元配列にしたときの 4 番目の要素
b.flat[4]

5

In [19]:
# 複素数を要素とする ndarray インスタンス
c = np.array([1.-2.6j, 2.1+3.J, 4.-3.2])
c.real

array([1. , 2.1, 0.8])

In [21]:
c.imag

array([-2.6,  3. ,  0. ])

In [69]:
print(f"a の要素の数: {a.size}")
print(f"b の要素の数: {b.size}")
print(f"c の要素の数: {c.size}")
print(f"a の要素1つ1つのバイト数: {a.itemsize}")
print(f"b の要素1つ1つのバイト数: {b.itemsize}")
# 複素数を含む方が要素1つあたりのバイト数が大きい
print(f"c の要素1つ1つのバイト数: {c.itemsize}")
print(f"a のndarray全体のバイト数: {a.nbytes}")
print(f"b のndarray全体のバイト数: {b.nbytes}")
print(f"c のndarray全体のバイト数: {c.nbytes}")

print(f".nbytes == .size * .itemsize: {a.nbytes == a.size * a.itemsize}")

a の要素の数: 3
b の要素の数: 6
c の要素の数: 3
a の要素1つ1つのバイト数: 8
b の要素1つ1つのバイト数: 8
c の要素1つ1つのバイト数: 16
a のndarray全体のバイト数: 24
b のndarray全体のバイト数: 48
c のndarray全体のバイト数: 48
.nbytes == .size * .itemsize: True


In [94]:
print(f"a の次元数: {a.ndim}")
print(f"b の次元数: {b.ndim}")
print(f"c の次元数: {c.ndim}")
print(f"a の形状　: {a.shape}")
print(f"b の形状　: {b.shape}")
print(f"c の形状　: {c.shape}")


a の次元数: 1
b の次元数: 2
c の次元数: 1
a の形状　: (3,)
b の形状　: (2, 3)
c の形状　: (3,)


In [99]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False